
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.100.0/24
    - 10.42.1.0/24
    - 10.42.2.0/24

light:
  - platform: niko_home_control
    host: 192.168.100.25

binary_sensor:
  - platform: remote_rpi_gpio
    host: 10.42.1.1
    ports:
      27: test switch

switch:
  - platform: remote_rpi_gpio
    host: 10.42.1.1
    ports:
      17: test led