---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: media-vlan
  namespace: kestro-media
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "master": "eth0.100",
          "mode": "bridge",
          "ipam": {
            "type": "dhcp"
          }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gerbera
  namespace: kestro-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gerbera
  template:
    metadata:
      labels:
        app: gerbera
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
              { "name": "media-vlan",
                "interface": "media0",
                "mac": "b8:27:eb:ca:ab:80"
              }]'
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: gerbera
          image: gerbera/gerbera:sha-1f23105
          ports:
          - name: http
            protocol: TCP
            containerPort: 49494
          - name: upnp
            protocol: UDP
            containerPort: 1900
          volumeMounts:
          - name: gerbera-home
            mountPath: /root
          - name: gerbera-config
            mountPath: /var/run/gerbera/
          - name: kestro-music
            mountPath: /media/music
      volumes:
      - name: gerbera-home
        nfs:
          server: rpi4-k8s-master
          path: /srv/nfs/lib/gerbera/home
      - name: gerbera-config
        nfs:
          server: rpi4-k8s-master
          path: /srv/nfs/lib/gerbera/config
      - name: kestro-music
        nfs:
          server: rpi4-k8s-master
          path: /srv/nfs/music
---
kind: Service 
apiVersion: v1
metadata:
  name: gerbera-ui
  namespace: kestro-media
spec:
  ports:
    - name: http
      protocol: TCP
      port: 49494
      targetPort: 49494
---
apiVersion: v1
kind: Endpoints
metadata:
  name: gerbera-ui
  namespace: kestro-media
subsets:
  - addresses:
      - ip: 192.168.100.32
    ports:
      - name: http
        protocol: TCP
        port: 49494
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gerbera-ui
  namespace: kestro-media
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`media.kestro.home`)
    services:
    - name: gerbera-ui
      port: 49494
  tls:
    secretName: tls-media
