---
apiVersion: v1
kind: Pod
metadata:
  namespace: kestro-media
  name: pod-case-02
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-kestromedia",
              "interface": "media0",
              "mac": "c2:b0:57:49:48:f2"
            }
            ]'
spec:
  nodeName: rpi-mancave
  containers:
  - name: pod-case-02
    image: janvolck/tools:latest-armv7
    command:
    - /sbin/init
    volumeMounts:
    - name: kestro-music
      mountPath: /media/music
  volumes:
  - name: kestro-music
    nfs:
      server: rpi4-k8s-master
      path: /srv/nfs/music