---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eap-deployment
  namespace: kestro
  labels:
    app: kestro-eap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kestro-eap
  template:
    metadata:
      labels:
        app: kestro-eap
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
              { "name": "admin-vlan",
                "interface": "admin0",
                "mac": "b8:27:eb:ca:ab:6e"
              },
              { "name": "default-macvlan",
                "ips": [ "192.168.0.30/24"],
                "interface": "default0",
                "mac": "b8:27:eb:ca:ab:6c"
              },
              { "name": "default-macvlan",
                "ips": [ "192.168.1.30/24"],
                "interface": "default1",
                "mac": "b8:27:eb:ca:ab:6d"
              }]'
    spec:
      containers:
      - name: omada-controller
        image: mbentley/omada-controller:3.2-armv7l
        ports:
        - name: http
          protocol: TCP
          containerPort: 8088
        - name: https
          protocol: TCP
          containerPort: 8043
        - protocol: UDP
          containerPort: 27001
        - protocol: TCP
          containerPort: 27002
        - protocol: UDP
          containerPort: 29810
        - protocol: TCP
          containerPort: 29811
        - protocol: TCP
          containerPort: 29812
        - protocol: TCP
          containerPort: 29813
        volumeMounts:
        - mountPath: /opt/tplink/EAPController/data
          name: eapcontroller-data
        - mountPath: /opt/tplink/EAPController/work
          name: eapcontroller-work
        - mountPath: /opt/tplink/EAPController/logs
          name: eapcontroller-logs
        resources:
          limits: 
            memory: 256Mi
            cpu: "1"
          requests:
            memory: 128Mi
            cpu: "1"
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /login
            port: 8043
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: eapcontroller-data
        hostPath:
          path: "/var/eap/data"
      - name: eapcontroller-work
        hostPath:
          path: "/var/eap/work"
      - name: eapcontroller-logs
        hostPath:
          path: "/var/log/eap"
---
kind: Service 
apiVersion: v1 
metadata:
  name: eapcontroller-web
  namespace: kestro
spec:
  selector:
    app: kestro-eap 
  ports:
    - name: http
      protocol: TCP
      port: 8088
      targetPort: 8088
    - name: https
      protocol: TCP
      port: 8043
      targetPort: 8043
---
kind: Service 
apiVersion: v1 
metadata:
  name: eapcontroller-service
  namespace: kestro
spec:
  selector:
    app: kestro-eap 
  ports:
    - name: searching
      protocol: TCP
      port: 27002
      targetPort: 27002
    - name: mgmt
      protocol: TCP
      port: 29811
      targetPort: 29811
    - name: adaption
      protocol: TCP
      port: 29812
      targetPort: 29812
    - name: upgrading
      protocol: TCP
      port: 29813
      targetPort: 29813
---
kind: Service 
apiVersion: v1 
metadata:
  name: eapdiscovery-service
  namespace: kestro
spec:
  selector:
    app: kestro-eap 
  ports:
    - name: controller
      protocol: UDP
      port: 27001
      targetPort: 27001
    - name: eap
      protocol: UDP
      port: 29810
      targetPort: 29810
