logs:
  general:
    level: INFO

ingressRoute:
  dashboard:
    enabled: false

additionalArguments:
  - "--log.level=INFO"
  - "--accesslog=true"
  - "--api=true"
  - "--api.dashboard=true"
  - "--entrypoints.mqtt.address=:1883/tcp"
  - "--entrypoints.zabbixtrapper.address=:10051/tcp"
  - "--serverstransport.insecureskipverify=true"

ports:
  mqtt:
    port: 1883
    protocol: TCP
    expose:
      default: true
    exposedPort: 1883
  zabbixtrapper:
    port: 10051
    protocol: TCP
    expose:
      default: true
    exposedPort: 10051
